apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672   # Internal Cluster Port
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672  # Management UI
      targetPort: 15672

