apiVersion: v1
kind: Service
metadata:
  name: vclass-backend-service
spec:
  selector:
    name: vclass-backend
    app: flask
  ports:
    - protocol: TCP
      port: 5000  
      targetPort: 5000  
  type: NodePort  
